services:
  - type: web
    name: eventapp-server
    env: node
    plan: starter
    buildCommand: cd server && npm install && npm audit fix --force
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYSTACK_SECRET
        sync: false

  - type: web
    name: eventapp-client
    env: static
    plan: starter
    buildCommand: cd client && npm install && npm audit fix --force && npm run build
    staticPublishPath: client/build
